DATA:
  IMG_SIZE: 512
MODEL:
  TYPE: iwin
  NAME: iwin_small_patch4_window16_512_finetune
  DROP_PATH_RATE: 0.3
  IWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 3, 4, 8, 16 ]
    WINDOW_SIZE: 16
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False