DATA:
  IMG_SIZE: 384
MODEL:
  TYPE: iwin
  NAME: iwin_large_patch4_window12_384_22kto1k_finetune
  DROP_PATH_RATE: 0.2
  IWIN:
    EMBED_DIM: 192
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 6, 12, 24, 48 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 30
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False